import mathgenerator as mg
import helper
import os
import datetime
from FileFormatter import TestFile

# CREATES A SOLVER TEST JSON FILE FOR EACH PROBLEM GENERATED BY THE MATHGENERATOR LIBRARY
# AND PUTS THEM ALL INTO THE JSON_MATH_TESTS DIRECTORY

if __name__ == "__main__":
	helper.directory_init("json_math_tests")
	os.chdir("json_math_tests")						# mathbot_testing/json_math_tests

	genList = mg.getGenList()
	for i in range(len(genList) - 110):
		tests = []
		numTests = 2
		for j in range(numTests):
			question, expected = mg.genById(i)
			question = question.strip()
			tests.append([question, expected])
			# verify that this works, and robust it up
			# IDEA: after a question is tested, keep track of if it didn't parse...
			#		make a separate file that contains the variations of questions that could be asked
			#		then maybe make a script to test those questions at the users discretion

			
		solver = genList[i][3]

		testFile = TestFile(solver, tests)
		testFile.writeFile()

	os.chdir("..")									# mathbot_testing
